# Generated by Django 5.2 on 2025-05-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0003_categoria_imagen_url_producto_imagen_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
