# Generated by Django 5.2 on 2025-05-09 19:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0005_valoracion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='categoria',
            new_name='categoria_id',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='producto',
            new_name='producto_id',
        ),
        migrations.RenameField(
            model_name='valoracion',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('producto_id', 'usuario_id')},
        ),
    ]
