# Generated by Django 5.2 on 2025-05-09 22:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('producto', '0007_rename_categoria_id_producto_categoria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='valoracion',
            old_name='producto_id',
            new_name='producto',
        ),
        migrations.AlterUniqueTogether(
            name='valoracion',
            unique_together={('producto', 'usuario')},
        ),
    ]
