# Generated by Django 5.2 on 2025-05-09 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='direccion',
            name='telefono',
            field=models.BigIntegerField(null=True),
        ),
    ]
