# Generated by Django 5.2 on 2025-05-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_direccion_telefono'),
    ]

    operations = [
        migrations.RenameField(
            model_name='direccion',
            old_name='usuario',
            new_name='usuario_id',
        ),
        migrations.AddField(
            model_name='direccion',
            name='es_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='telefono',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
